<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Zed.MediatR</PackageId>
    <Title>Zed.MediatR</Title>
    <AssemblyTitle>Zed.MediatR</AssemblyTitle>
    <Description>Zed.MediatR is a MediatR integration layer for the Zed library, providing pipeline behaviors such as FluentValidation integration.</Description>
    <PackageReleaseNotes>Zed.MediatR is a MediatR integration layer for the Zed library, providing pipeline behaviors such as FluentValidation integration.</PackageReleaseNotes>
    <Authors>ztepsic</Authors>
    <RequireLicenseAcceptance>false</RequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ztepsic/zed</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ztepsic/zed</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Zed MediatR FluentValidation DDD</PackageTags>
    <Copyright>Copyright 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zed\Zed.csproj" />
  </ItemGroup>

</Project>
