environment:
  version_major: 1
  version_minor: 2
  version_patch: 4
version: $(version_major).$(version_minor).$(version_patch).{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(version_major).0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(version_major).$(version_minor).$(version_patch)'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: Zed_build_nuget.bat
artifacts:
- path: packages
  name: Zed.Packages.$(APPVEYOR_BUILD_VERSION)
- path: Zed.$(APPVEYOR_BUILD_VERSION).nupkg
  name: Zed.$(APPVEYOR_BUILD_VERSION).nupkg