environment:
  version_major: 2
  version_minor: 0
  version_patch: 0
version: $(version_major).$(version_minor).$(version_patch).{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: false
  file: '**\AssemblyInfo.*'
  assembly_version: '$(version_major).0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(version_major).$(version_minor).$(version_patch)'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(version_major).$(version_minor).$(version_patch)'
  package_version: '{version}'
  assembly_version: '$(version_major).0.0.0'
  file_version: '{version}'
  informational_version: '$(version_major).$(version_minor).$(version_patch)'
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: Zed_build_nuget.bat
artifacts:
- path: Zed.$(version_major).$(version_minor).$(version_patch).nupkg
  name: Zed.$(version_major).$(version_minor).$(version_patch).nupkg